# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernstein_copula_pdf <- function(u, v, R) {
    .Call(`_BernsteinCopula_bernstein_copula_pdf`, u, v, R)
}

bernstein_estep <- function(u, v, R, prior, tau) {
    .Call(`_BernsteinCopula_bernstein_estep`, u, v, R, prior, tau)
}

bernstein_estep_with_weight <- function(u, v, du, dv, R, prior, tau, exw1, exw2, eyw1, eyw2) {
    .Call(`_BernsteinCopula_bernstein_estep_with_weight`, u, v, du, dv, R, prior, tau, exw1, exw2, eyw1, eyw2)
}

bernstein_estep_group <- function(u, v, R, N, prior, tau) {
    .Call(`_BernsteinCopula_bernstein_estep_group`, u, v, R, N, prior, tau)
}

bernstein_estep_group_with_weight <- function(u, v, R, N, prior, tau, exw1, exw2, eyw1, eyw2) {
    .Call(`_BernsteinCopula_bernstein_estep_group_with_weight`, u, v, R, N, prior, tau, exw1, exw2, eyw1, eyw2)
}

dbinom_loader <- function(n, p) {
    .Call(`_BernsteinCopula_dbinom_loader`, n, p)
}

dbinom_loader_inplace <- function(n, p, P) {
    invisible(.Call(`_BernsteinCopula_dbinom_loader_inplace`, n, p, P))
}

dou_mstep <- function(tau_bar, maxiter = 1000L, tol = 1e-10) {
    .Call(`_BernsteinCopula_dou_mstep`, tau_bar, maxiter, tol)
}

emstep_exponential <- function(x, w1, w2, params) {
    .Call(`_BernsteinCopula_emstep_exponential`, x, w1, w2, params)
}

emstep_exponential_group <- function(x, w1, w2, params) {
    .Call(`_BernsteinCopula_emstep_exponential_group`, x, w1, w2, params)
}

emstep_normal <- function(x, w1, w2, params) {
    .Call(`_BernsteinCopula_emstep_normal`, x, w1, w2, params)
}

emstep_normal_group <- function(x, w1, w2, params) {
    .Call(`_BernsteinCopula_emstep_normal_group`, x, w1, w2, params)
}

emstep_ph_build_interval_data <- function(x, w1, w2) {
    .Call(`_BernsteinCopula_emstep_ph_build_interval_data`, x, w1, w2)
}

emstep_ph_build_interval_data_group <- function(x, w1, w2) {
    .Call(`_BernsteinCopula_emstep_ph_build_interval_data_group`, x, w1, w2)
}

sinkhorn_scaling <- function(W, maxiter = 1000L, tol = 1e-10) {
    .Call(`_BernsteinCopula_sinkhorn_scaling`, W, maxiter, tol)
}

