# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernstein_copula_pdf <- function(u, v, R) {
    .Call(`_BernsteinCopula_bernstein_copula_pdf`, u, v, R)
}

bernstein_emloop <- function(u, v, R_init, tau_bar_init, options) {
    .Call(`_BernsteinCopula_bernstein_emloop`, u, v, R_init, tau_bar_init, options)
}

bernstein_estep <- function(u, v, R, tau) {
    .Call(`_BernsteinCopula_bernstein_estep`, u, v, R, tau)
}

bernstein_estep_with_weight <- function(u, v, R, tau, ew) {
    .Call(`_BernsteinCopula_bernstein_estep_with_weight`, u, v, R, tau, ew)
}

dbinom_loader <- function(n, p) {
    .Call(`_BernsteinCopula_dbinom_loader`, n, p)
}

dbinom_loader_inplace <- function(n, p, P) {
    invisible(.Call(`_BernsteinCopula_dbinom_loader_inplace`, n, p, P))
}

dou_mstep <- function(tau_bar, maxiter = 1000L, tol = 1e-10) {
    .Call(`_BernsteinCopula_dou_mstep`, tau_bar, maxiter, tol)
}

sinkhorn_scaling <- function(W, maxiter = 1000L, tol = 1e-10) {
    .Call(`_BernsteinCopula_sinkhorn_scaling`, W, maxiter, tol)
}

